/**
 * awslib stdlib macro -> mxgraph shape key mapping.
 *
 * Auto-generated from temp/awslib-mxgraph-mapping.json + docs/awslib-aws4-composite-map.json.
 * 674 sprites matched, 137 unresolved.
 * DO NOT EDIT MANUALLY -- re-run temp/gen-awslib-macros.py to regenerate.
 */

export interface AwslibMacroInfo {
  /** DrawIO/mxgraph shape key, e.g. 'mxgraph.aws4.ec2' */
  shapeKey: string;
  /** AWS4 composite icon overlay stencil key, e.g. 'mxgraph.aws4.ec2'. */
  resIcon?: string;
  /** AWS4 composite icon background fill color, e.g. '#ED7100'. */
  fillColor?: string;
  /** AWS4 composite icon background stroke color, e.g. '#ffffff'. */
  strokeColor?: string;
}

// AWS service category colors
const RED = '#DD344C';       // Security, Mobile, Front-End
const PINK = '#E7157B';      // App Integration, Management
const ORANGE = '#ED7100';    // Compute
const GREEN = '#7AA116';     // Storage
const TEAL = '#01A88D';      // IoT, Blockchain
const CYAN = '#00A4A6';      // Region, VPC, Subnet
const BLUE = '#3334B9';      // Database, Developer Tools
const PURPLE = '#8C4FFF';    // Networking, Analytics
const MAGENTA = '#C925D1';   // Cloud
const DARK = '#1E262E';      // General
const GRAY = '#7D8998';      // Corporate Data Center
const WHITE = '#ffffff';

// Sprites with a confirmed mxgraph shape mapping
const AWSLIB_MACROS: Record<string, AwslibMacroInfo> = {
  'APIGateway': { shapeKey: 'mxgraph.aws4.api_gateway', fillColor: PINK },
  'APIGatewayEndpoint': { shapeKey: 'mxgraph.aws4.endpoint' },
  'AWSManagementConsole': { shapeKey: 'mxgraph.aws4.management_console2' },
  'Alert': { shapeKey: 'mxgraph.aws4.alert' },
  'AlexaForBusiness': { shapeKey: 'mxgraph.aws4.alexa_for_business', fillColor: RED },
  'Amplify': { shapeKey: 'mxgraph.aws4.amplify', fillColor: RED },
  'AmplifyAWSAmplifyStudio': { shapeKey: 'mxgraph.aws4.amplify_aws_amplify_studio' },
  'Analytics': { shapeKey: 'mxgraph.aws4.analytics', fillColor: PURPLE },
  'AppConfig': { shapeKey: 'mxgraph.aws4.app_config', fillColor: PINK },
  'AppMesh': { shapeKey: 'mxgraph.aws4.app_mesh', fillColor: PURPLE },
  'AppMeshMesh': { shapeKey: 'mxgraph.aws4.mesh' },
  'AppMeshVirtualGateway': { shapeKey: 'mxgraph.aws4.virtual_gateway' },
  'AppMeshVirtualNode': { shapeKey: 'mxgraph.aws4.virtual_node' },
  'AppMeshVirtualRouter': { shapeKey: 'mxgraph.aws4.virtual_router' },
  'AppMeshVirtualService': { shapeKey: 'mxgraph.aws4.virtual_service' },
  'AppStream': { shapeKey: 'mxgraph.aws4.appstream_20', fillColor: TEAL },
  'AppSync': { shapeKey: 'mxgraph.aws4.appsync', fillColor: PINK },
  'ApplicationAutoScaling': { shapeKey: 'mxgraph.aws4.application_auto_scaling', fillColor: ORANGE },
  'ApplicationAutoScaling2': { shapeKey: 'mxgraph.aws4.application_auto_scaling', fillColor: PINK },
  'ApplicationCostProfiler': { shapeKey: 'mxgraph.aws4.application_cost_profiler', fillColor: GREEN },
  'ApplicationDiscoveryService': { shapeKey: 'mxgraph.aws4.application_discovery_service', fillColor: TEAL },
  'ApplicationIntegration': { shapeKey: 'mxgraph.aws4.application_integration', fillColor: PINK },
  'ApplicationMigrationService': { shapeKey: 'mxgraph.aws4.cloudendure_migration', fillColor: TEAL },
  'Artifact': { shapeKey: 'mxgraph.aws4.artifact', fillColor: RED },
  'Athena': { shapeKey: 'mxgraph.aws4.athena', fillColor: PURPLE },
  'AuditManager': { shapeKey: 'mxgraph.aws4.audit_manager', fillColor: RED },
  'Aurora': { shapeKey: 'mxgraph.aws4.aurora', fillColor: BLUE },
  'AuroraAmazonAuroraInstancealternate': { shapeKey: 'mxgraph.aws4.aurora_instance_alt', strokeColor: BLUE },
  'AuroraAmazonRDSInstance': { shapeKey: 'mxgraph.aws4.rds_instance', strokeColor: BLUE },
  'AuroraAmazonRDSInstanceAternate': { shapeKey: 'mxgraph.aws4.rds_instance_alt', strokeColor: BLUE },
  'AuroraInstance': { shapeKey: 'mxgraph.aws4.aurora_instance', strokeColor: BLUE },
  'AuroraMariaDBInstance': { shapeKey: 'mxgraph.aws4.rds_mariadb_instance', strokeColor: BLUE },
  'AuroraMariaDBInstanceAlternate': { shapeKey: 'mxgraph.aws4.rds_mariadb_instance_alt', strokeColor: BLUE },
  'AuroraMySQLInstance': { shapeKey: 'mxgraph.aws4.rds_mysql_instance', strokeColor: BLUE },
  'AuroraMySQLInstanceAlternate': { shapeKey: 'mxgraph.aws4.rds_mysql_instance_alt', strokeColor: BLUE },
  'AuroraOracleInstance': { shapeKey: 'mxgraph.aws4.rds_oracle_instance', strokeColor: BLUE },
  'AuroraOracleInstanceAlternate': { shapeKey: 'mxgraph.aws4.rds_oracle_instance_alt', strokeColor: BLUE },
  'AuroraPIOPSInstance': { shapeKey: 'mxgraph.aws4.rds_piops', strokeColor: BLUE },
  'AuroraPostgreSQLInstance': { shapeKey: 'mxgraph.aws4.rds_postgresql_instance', strokeColor: BLUE },
  'AuroraPostgreSQLInstanceAlternate': { shapeKey: 'mxgraph.aws4.rds_postgresql_instance_alt', strokeColor: BLUE },
  'AuroraSQLServerInstance': { shapeKey: 'mxgraph.aws4.rds_sql_server_instance', strokeColor: BLUE },
  'AuroraSQLServerInstanceAlternate': { shapeKey: 'mxgraph.aws4.rds_sql_server_instance_alt', strokeColor: BLUE },
  'AutoScaling': { shapeKey: 'mxgraph.aws4.autoscaling', fillColor: PINK },
  'AutoScalingGroup': { shapeKey: 'mxgraph.aws4.group_auto_scaling_group' },
  'BackintAgent': { shapeKey: 'mxgraph.aws4.backint_agent', fillColor: PINK },
  'Backup': { shapeKey: 'mxgraph.aws4.backup', fillColor: GREEN },
  'BackupAWSBackupsupportforAmazonFSxforNetAppONTAP': { shapeKey: 'mxgraph.aws4.aws_backup_support_for_amazon_fsx_for_netapp_ontap' },
  'BackupAWSBackupsupportforAmazonS3': { shapeKey: 'mxgraph.aws4.backup_aws_backup_support_for_amazon_s3' },
  'BackupBackupPlan': { shapeKey: 'mxgraph.aws4.backup_plan' },
  'BackupBackupRestore': { shapeKey: 'mxgraph.aws4.backup_restore' },
  'BackupBackupVault': { shapeKey: 'mxgraph.aws4.backup_vault' },
  'BackupComplianceReporting': { shapeKey: 'mxgraph.aws4.backup_compliance_reporting' },
  'BackupCompute': { shapeKey: 'mxgraph.aws4.backup_compute' },
  'BackupDatabase': { shapeKey: 'mxgraph.aws4.backup_database' },
  'BackupGateway': { shapeKey: 'mxgraph.aws4.backup_gateway' },
  'BackupRecoveryPointObjective': { shapeKey: 'mxgraph.aws4.backup_recovery_point_objective' },
  'BackupRecoveryTimeObjective': { shapeKey: 'mxgraph.aws4.backup_recovery_time_objective' },
  'BackupStorage': { shapeKey: 'mxgraph.aws4.backup_storage' },
  'BackupVirtualMachine': { shapeKey: 'mxgraph.aws4.backup_virtual_machine' },
  'BackupVirtualMachineMonitor': { shapeKey: 'mxgraph.aws4.backup_virtual_machine_monitor' },
  'Batch': { shapeKey: 'mxgraph.aws4.batch', fillColor: ORANGE },
  'Blockchain': { shapeKey: 'mxgraph.aws4.blockchain', fillColor: ORANGE },
  'BusinessApplications': { shapeKey: 'mxgraph.aws4.business_application', fillColor: RED },
  'Camera': { shapeKey: 'mxgraph.aws4.camera2' },
  'CertificateManager': { shapeKey: 'mxgraph.aws4.certificate_manager_3', fillColor: RED },
  'CertificateManagerCertificateAuthority': { shapeKey: 'mxgraph.aws4.certificate_manager_2' },
  'Chat': { shapeKey: 'mxgraph.aws4.chat' },
  'Chatbot': { shapeKey: 'mxgraph.aws4.chatbot', fillColor: PINK },
  'Chime': { shapeKey: 'mxgraph.aws4.chime', fillColor: RED },
  'ChimeSDK': { shapeKey: 'mxgraph.aws4.chime_sdk', fillColor: RED },
  'ChimeVoiceConnector': { shapeKey: 'mxgraph.aws4.chime', fillColor: RED },
  'Client': { shapeKey: 'mxgraph.aws4.client' },
  'ClientVPN': { shapeKey: 'mxgraph.aws4.client_vpn', fillColor: PURPLE },
  'Cloud': { shapeKey: 'mxgraph.aws4.group_aws_cloud', strokeColor: DARK },
  'Cloud9': { shapeKey: 'mxgraph.aws4.cloud9', fillColor: BLUE },
  'Cloud9Cloud9': { shapeKey: 'mxgraph.aws4.cloud9', strokeColor: BLUE },
  'CloudDigitalInterface': { shapeKey: 'mxgraph.aws4.cloud_digital_interface' },
  'CloudDirectory': { shapeKey: 'mxgraph.aws4.cloud_directory', fillColor: RED },
  'CloudDirectory2': { shapeKey: 'mxgraph.aws4.cloud_directory', fillColor: PURPLE },
  'CloudEndureDisasterRecovery': { shapeKey: 'mxgraph.aws4.cloudendure_disaster_recovery', fillColor: GREEN },
  'CloudFormation': { shapeKey: 'mxgraph.aws4.cloudformation', fillColor: PINK },
  'CloudFormationChangeSet': { shapeKey: 'mxgraph.aws4.change_set' },
  'CloudFormationStack': { shapeKey: 'mxgraph.aws4.stack' },
  'CloudFormationTemplate': { shapeKey: 'mxgraph.aws4.template' },
  'CloudFront': { shapeKey: 'mxgraph.aws4.cloudfront', fillColor: PURPLE },
  'CloudFrontDownloadDistribution': { shapeKey: 'mxgraph.aws4.download_distribution' },
  'CloudFrontEdgeLocation': { shapeKey: 'mxgraph.aws4.edge_location' },
  'CloudFrontFunctions': { shapeKey: 'mxgraph.aws4.cloudfront_functions' },
  'CloudFrontStreamingDistribution': { shapeKey: 'mxgraph.aws4.streaming_distribution' },
  'CloudHSM': { shapeKey: 'mxgraph.aws4.cloudhsm', fillColor: RED },
  'CloudMapNamespace': { shapeKey: 'mxgraph.aws4.namespace' },
  'CloudMapResource': { shapeKey: 'mxgraph.aws4.cloud_map_resource', strokeColor: PURPLE },
  'CloudSearch': { shapeKey: 'mxgraph.aws4.cloudsearch2', fillColor: PURPLE },
  'CloudSearchSearchDocuments': { shapeKey: 'mxgraph.aws4.search_documents' },
  'CloudTrail': { shapeKey: 'mxgraph.aws4.cloudtrail', fillColor: PINK },
  'CloudWAN': { shapeKey: 'mxgraph.aws4.cloud_wan', fillColor: PURPLE },
  'CloudWANCoreNetworkEdge': { shapeKey: 'mxgraph.aws4.cloud_wan_virtual_pop' },
  'CloudWANSegmentNetwork': { shapeKey: 'mxgraph.aws4.cloud_wan_segment_network' },
  'CloudWANVirtualPoP': { shapeKey: 'mxgraph.aws4.cloud_wan_virtual_pop' },
  'CloudWatch': { shapeKey: 'mxgraph.aws4.cloudwatch_2', fillColor: PINK },
  'CloudWatchAlarm': { shapeKey: 'mxgraph.aws4.alarm' },
  'CloudWatchEventEventBased': { shapeKey: 'mxgraph.aws4.event_event_based' },
  'CloudWatchEventTimeBased': { shapeKey: 'mxgraph.aws4.event_time_based' },
  'CloudWatchEvidently': { shapeKey: 'mxgraph.aws4.cloudwatch_evidently' },
  'CloudWatchLogs': { shapeKey: 'mxgraph.aws4.cloudwatch_logs' },
  'CloudWatchMetricsInsights': { shapeKey: 'mxgraph.aws4.cloudwatch_metrics_insights' },
  'CloudWatchRUM': { shapeKey: 'mxgraph.aws4.cloudwatch_rum' },
  'CloudWatchRule': { shapeKey: 'mxgraph.aws4.rule_2' },
  'CloudWatchSynthetics': { shapeKey: 'mxgraph.aws4.cloudwatch_synthetics' },
  'CodeArtifact': { shapeKey: 'mxgraph.aws4.codeartifact', fillColor: BLUE },
  'CodeBuild': { shapeKey: 'mxgraph.aws4.codebuild', fillColor: BLUE },
  'CodeCommit': { shapeKey: 'mxgraph.aws4.codecommit', fillColor: BLUE },
  'CodeDeploy': { shapeKey: 'mxgraph.aws4.codedeploy', fillColor: BLUE },
  'CodePipeline': { shapeKey: 'mxgraph.aws4.codepipeline', fillColor: BLUE },
  'CodeStar': { shapeKey: 'mxgraph.aws4.codestar', fillColor: BLUE },
  'Cognito': { shapeKey: 'mxgraph.aws4.cognito', fillColor: RED },
  'Compute': { shapeKey: 'mxgraph.aws4.compute', fillColor: ORANGE },
  'Config': { shapeKey: 'mxgraph.aws4.config', fillColor: PINK },
  'Connect': { shapeKey: 'mxgraph.aws4.connect', fillColor: RED },
  'ConsoleMobileApplication': { shapeKey: 'mxgraph.aws4.mobile_application', fillColor: PINK },
  'CorporateDataCenter': { shapeKey: 'mxgraph.aws4.corporate_data_center2', fillColor: GRAY },
  'DataExchange': { shapeKey: 'mxgraph.aws4.data_exchange', fillColor: PURPLE },
  'DataPipeline': { shapeKey: 'mxgraph.aws4.data_pipeline', fillColor: PURPLE },
  'DataSync': { shapeKey: 'mxgraph.aws4.datasync', fillColor: TEAL },
  'Database': { shapeKey: 'mxgraph.aws4.database', fillColor: BLUE },
  'DatabaseMigrationService': { shapeKey: 'mxgraph.aws4.database_migration_service', fillColor: BLUE },
  'DatabaseMigrationServiceDatabasemigrationworkflowjob': { shapeKey: 'mxgraph.aws4.database_migration_workflow_job', strokeColor: BLUE },
  'DatasyncAgent': { shapeKey: 'mxgraph.aws4.agent2' },
  'DeepLearningAMIs': { shapeKey: 'mxgraph.aws4.deep_learning_amis', fillColor: TEAL },
  'DevOpsGuru': { shapeKey: 'mxgraph.aws4.devops_guru', fillColor: TEAL },
  'DevOpsGuruInsights': { shapeKey: 'mxgraph.aws4.devops_guru_insights' },
  'DeviceFarm': { shapeKey: 'mxgraph.aws4.device_farm', fillColor: RED },
  'DirectConnect': { shapeKey: 'mxgraph.aws4.direct_connect', fillColor: PURPLE },
  'DirectConnectGateway': { shapeKey: 'mxgraph.aws4.gateway', strokeColor: PURPLE },
  'DirectoryService': { shapeKey: 'mxgraph.aws4.directory_service', fillColor: RED },
  'DirectoryServiceADConnector': { shapeKey: 'mxgraph.aws4.ad_connector' },
  'DirectoryServiceAWSManagedMicrosoftAD': { shapeKey: 'mxgraph.aws4.managed_ms_ad' },
  'DirectoryServiceSimpleAD': { shapeKey: 'mxgraph.aws4.simple_ad' },
  'Disk': { shapeKey: 'mxgraph.aws4.disk' },
  'Document': { shapeKey: 'mxgraph.aws4.document' },
  'DocumentDB': { shapeKey: 'mxgraph.aws4.documentdb_with_mongodb_compatibility', fillColor: BLUE },
  'Documents': { shapeKey: 'mxgraph.aws4.documents' },
  'DynamoDB': { shapeKey: 'mxgraph.aws4.dynamodb', fillColor: BLUE },
  'DynamoDBAmazonDynamoDBAccelerator': { shapeKey: 'mxgraph.aws4.dynamodb_dax', strokeColor: BLUE },
  'DynamoDBAttribute': { shapeKey: 'mxgraph.aws4.attribute', strokeColor: BLUE },
  'DynamoDBAttributes': { shapeKey: 'mxgraph.aws4.attributes', strokeColor: BLUE },
  'DynamoDBGlobalsecondaryindex': { shapeKey: 'mxgraph.aws4.global_secondary_index', strokeColor: BLUE },
  'DynamoDBItem': { shapeKey: 'mxgraph.aws4.item', strokeColor: BLUE },
  'DynamoDBItems': { shapeKey: 'mxgraph.aws4.items', strokeColor: BLUE },
  'DynamoDBStandardAccessTableClass': { shapeKey: 'mxgraph.aws4.dynamodb_standard_access_table_class', strokeColor: BLUE },
  'DynamoDBStandardInfrequentAccessTableClass': { shapeKey: 'mxgraph.aws4.dynamodb_standard_infrequent_access_table_class', strokeColor: BLUE },
  'DynamoDBStream': { shapeKey: 'mxgraph.aws4.dynamodb_stream', strokeColor: BLUE },
  'DynamoDBTable': { shapeKey: 'mxgraph.aws4.table', strokeColor: BLUE },
  'EC2': { shapeKey: 'mxgraph.aws4.ec2', fillColor: ORANGE },
  'EC2A1Instance': { shapeKey: 'mxgraph.aws4.a1_instance' },
  'EC2AMI': { shapeKey: 'mxgraph.aws4.ami' },
  'EC2AWSInferentia': { shapeKey: 'mxgraph.aws4.inferentia' },
  'EC2AWSMicroserviceExtractorforNET': { shapeKey: 'mxgraph.aws4.ec2_aws_microservice_extractor_for_net' },
  'EC2AutoScaling': { shapeKey: 'mxgraph.aws4.auto_scaling2', fillColor: ORANGE },
  'EC2AutoScalingResource': { shapeKey: 'mxgraph.aws4.auto_scaling2' },
  'EC2C4Instance': { shapeKey: 'mxgraph.aws4.c4_instance' },
  'EC2C5Instance': { shapeKey: 'mxgraph.aws4.c5_instance' },
  'EC2C5aInstance': { shapeKey: 'mxgraph.aws4.c5a' },
  'EC2C5adInstance': { shapeKey: 'mxgraph.aws4.c5ad' },
  'EC2C5dInstance': { shapeKey: 'mxgraph.aws4.c5d' },
  'EC2C5nInstance': { shapeKey: 'mxgraph.aws4.c5n_instance' },
  'EC2C6aInstance': { shapeKey: 'mxgraph.aws4.ec2_c6a_instance' },
  'EC2C6gInstance': { shapeKey: 'mxgraph.aws4.c6g_instance' },
  'EC2C6gdInstance': { shapeKey: 'mxgraph.aws4.c6gd' },
  'EC2C6gnInstance': { shapeKey: 'mxgraph.aws4.ec2_c6gn_instance' },
  'EC2C6iInstance': { shapeKey: 'mxgraph.aws4.ec2_c6i_instance' },
  'EC2C7gInstance': { shapeKey: 'mxgraph.aws4.ec2_c7g_instance' },
  'EC2D2Instance': { shapeKey: 'mxgraph.aws4.d2_instance' },
  'EC2D3Instance': { shapeKey: 'mxgraph.aws4.d3_instance' },
  'EC2D3enInstance': { shapeKey: 'mxgraph.aws4.d3en_instance' },
  'EC2DBInstance': { shapeKey: 'mxgraph.aws4.db_on_instance2' },
  'EC2DL1Instance': { shapeKey: 'mxgraph.aws4.ec2_dl1_instance' },
  'EC2ElasticIPAddress': { shapeKey: 'mxgraph.aws4.elastic_ip_address' },
  'EC2F1Instance': { shapeKey: 'mxgraph.aws4.f1_instance' },
  'EC2G3Instance': { shapeKey: 'mxgraph.aws4.g3_instance' },
  'EC2G4adInstance': { shapeKey: 'mxgraph.aws4.g4ad_instance' },
  'EC2G4dnInstance': { shapeKey: 'mxgraph.aws4.g4dn' },
  'EC2G5Instance': { shapeKey: 'mxgraph.aws4.ec2_g5_instance' },
  'EC2G5gInstance': { shapeKey: 'mxgraph.aws4.ec2_g5g_instance' },
  'EC2H1Instance': { shapeKey: 'mxgraph.aws4.h1_instance' },
  'EC2HMIInstance': { shapeKey: 'mxgraph.aws4.high_memory_instance' },
  'EC2HabanaGaudiInstance': { shapeKey: 'mxgraph.aws4.habana_gaudi' },
  'EC2Hpc6aInstance': { shapeKey: 'mxgraph.aws4.ec2_hpc6a_instance' },
  'EC2I2Instance': { shapeKey: 'mxgraph.aws4.i2' },
  'EC2I3Instance': { shapeKey: 'mxgraph.aws4.i3_instance' },
  'EC2I3enInstance': { shapeKey: 'mxgraph.aws4.i3en' },
  'EC2I4iInstance': { shapeKey: 'mxgraph.aws4.ec2_i4i_instance' },
  'EC2Im4gnInstance': { shapeKey: 'mxgraph.aws4.ec2_im4gn_instance' },
  'EC2ImageBuilder': { shapeKey: 'mxgraph.aws4.ec2_image_builder', fillColor: ORANGE },
  'EC2Inf1Instance': { shapeKey: 'mxgraph.aws4.f1_instance' },
  'EC2Instance': { shapeKey: 'mxgraph.aws4.ec2_instance_contents' },
  'EC2InstanceContainer': { shapeKey: 'mxgraph.aws4.ec2_instance_contents', fillColor: ORANGE },
  'EC2Instances': { shapeKey: 'mxgraph.aws4.instances' },
  'EC2InstancewithCloudWatch': { shapeKey: 'mxgraph.aws4.instance_with_cloudwatch' },
  'EC2Is4genInstance': { shapeKey: 'mxgraph.aws4.ec2_is4gen_instance' },
  'EC2M1MacInstance': { shapeKey: 'mxgraph.aws4.ec2_m1_mac_instance' },
  'EC2M4Instance': { shapeKey: 'mxgraph.aws4.m4_instance' },
  'EC2M5Instance': { shapeKey: 'mxgraph.aws4.m5_instance' },
  'EC2M5aInstance': { shapeKey: 'mxgraph.aws4.m5a_instance' },
  'EC2M5dInstance': { shapeKey: 'mxgraph.aws4.m5d_instance' },
  'EC2M5dnInstance': { shapeKey: 'mxgraph.aws4.m5dn_instance' },
  'EC2M5nInstance': { shapeKey: 'mxgraph.aws4.m5n_instance' },
  'EC2M5znInstance': { shapeKey: 'mxgraph.aws4.m5zn_instance' },
  'EC2M6aInstance': { shapeKey: 'mxgraph.aws4.ec2_m6a_instance' },
  'EC2M6gInstance': { shapeKey: 'mxgraph.aws4.m6g_instance' },
  'EC2M6gdInstance': { shapeKey: 'mxgraph.aws4.m6gd_instance' },
  'EC2M6iInstance': { shapeKey: 'mxgraph.aws4.ec2_m6i_instance' },
  'EC2MacInstance': { shapeKey: 'mxgraph.aws4.mac_instance' },
  'EC2P2Instance': { shapeKey: 'mxgraph.aws4.p2_instance' },
  'EC2P3Instance': { shapeKey: 'mxgraph.aws4.p3_instance' },
  'EC2P3dnInstance': { shapeKey: 'mxgraph.aws4.p3dn_instance' },
  'EC2P4Instance': { shapeKey: 'mxgraph.aws4.p4_instance' },
  'EC2P4dInstance': { shapeKey: 'mxgraph.aws4.p4d_instance' },
  'EC2P4deInstance': { shapeKey: 'mxgraph.aws4.ec2_p4de_instance' },
  'EC2R4Instance': { shapeKey: 'mxgraph.aws4.r4_instance' },
  'EC2R5Instance': { shapeKey: 'mxgraph.aws4.r5_instance' },
  'EC2R5aInstance': { shapeKey: 'mxgraph.aws4.r5a_instance' },
  'EC2R5adInstance': { shapeKey: 'mxgraph.aws4.r5ad_instance' },
  'EC2R5bInstance': { shapeKey: 'mxgraph.aws4.r5b_instance' },
  'EC2R5dInstance': { shapeKey: 'mxgraph.aws4.r5d_instance' },
  'EC2R5gdInstance': { shapeKey: 'mxgraph.aws4.r5gd_instance' },
  'EC2R5nInstance': { shapeKey: 'mxgraph.aws4.r5n_instance' },
  'EC2R6gInstance': { shapeKey: 'mxgraph.aws4.r6g_instance' },
  'EC2R6iInstance': { shapeKey: 'mxgraph.aws4.ec2_r6i_instance' },
  'EC2RdnInstance': { shapeKey: 'mxgraph.aws4.rdn_instance' },
  'EC2Rescue': { shapeKey: 'mxgraph.aws4.rescue' },
  'EC2SpotInstance': { shapeKey: 'mxgraph.aws4.spot_instance' },
  'EC2T2Instance': { shapeKey: 'mxgraph.aws4.t2_instance' },
  'EC2T3Instance': { shapeKey: 'mxgraph.aws4.t3_instance' },
  'EC2T3aInstance': { shapeKey: 'mxgraph.aws4.t3a_instance' },
  'EC2T4gInstance': { shapeKey: 'mxgraph.aws4.t4g_instance' },
  'EC2TrainiumInstance': { shapeKey: 'mxgraph.aws4.trainium_instance' },
  'EC2Trn1Instance': { shapeKey: 'mxgraph.aws4.ec2_trn1_instance' },
  'EC2VT1Instance': { shapeKey: 'mxgraph.aws4.ec2_vt1_instance' },
  'EC2X1Instance': { shapeKey: 'mxgraph.aws4.x1_instance2' },
  'EC2X1eInstance': { shapeKey: 'mxgraph.aws4.x1e_instance' },
  'EC2X2gdInstance': { shapeKey: 'mxgraph.aws4.ec2_x2gd_instance' },
  'EC2X2idnInstance': { shapeKey: 'mxgraph.aws4.ec2_x2idn_instance' },
  'EC2X2iednInstance': { shapeKey: 'mxgraph.aws4.ec2_x2iedn_instance' },
  'EC2X2ieznInstance': { shapeKey: 'mxgraph.aws4.ec2_x2iezn_instance' },
  'EC2z1dInstance': { shapeKey: 'mxgraph.aws4.z1d_instance' },
  'ECSAnywhere': { shapeKey: 'mxgraph.aws4.ecs_anywhere', fillColor: ORANGE },
  'EFS': { shapeKey: 'mxgraph.aws4.elastic_file_system', fillColor: GREEN },
  'EMR': { shapeKey: 'mxgraph.aws4.emr', fillColor: PURPLE },
  'EMRCluster': { shapeKey: 'mxgraph.aws4.hdfs_cluster' },
  'EMREMREngine': { shapeKey: 'mxgraph.aws4.emr_engine' },
  'EMRHDFSCluster': { shapeKey: 'mxgraph.aws4.hdfs_cluster' },
  'ElastiCache': { shapeKey: 'mxgraph.aws4.elasticache', fillColor: BLUE },
  'ElastiCacheCacheNode': { shapeKey: 'mxgraph.aws4.cache_node', strokeColor: BLUE },
  'ElastiCacheElastiCacheforMemcached': { shapeKey: 'mxgraph.aws4.elasticache_for_memcached', strokeColor: BLUE },
  'ElastiCacheElastiCacheforRedis': { shapeKey: 'mxgraph.aws4.elasticache_for_redis', strokeColor: BLUE },
  'ElasticBeanstalk': { shapeKey: 'mxgraph.aws4.elastic_beanstalk', fillColor: ORANGE },
  'ElasticBeanstalkApplication': { shapeKey: 'mxgraph.aws4.application' },
  'ElasticBeanstalkContainer': { shapeKey: 'mxgraph.aws4.elastic_beanstalk', fillColor: ORANGE },
  'ElasticBeanstalkDeployment': { shapeKey: 'mxgraph.aws4.deployment' },
  'ElasticBlockStore': { shapeKey: 'mxgraph.aws4.elastic_block_store', fillColor: GREEN },
  'ElasticBlockStoreAmazonDataLifecycleManager': { shapeKey: 'mxgraph.aws4.elastic_block_store_amazon_data_lifecycle_manager' },
  'ElasticBlockStoreMultipleVolumes': { shapeKey: 'mxgraph.aws4.multiple_volumes_resource' },
  'ElasticBlockStoreSnapshot': { shapeKey: 'mxgraph.aws4.snapshot' },
  'ElasticBlockStoreVolume': { shapeKey: 'mxgraph.aws4.volume' },
  'ElasticBlockStoreVolumegp3': { shapeKey: 'mxgraph.aws4.elastic_block_store_volume_gp3' },
  'ElasticContainerRegistry': { shapeKey: 'mxgraph.aws4.ecr', fillColor: ORANGE },
  'ElasticContainerRegistryImage': { shapeKey: 'mxgraph.aws4.container_registry_image' },
  'ElasticContainerRegistryRegistry': { shapeKey: 'mxgraph.aws4.registry' },
  'ElasticContainerService': { shapeKey: 'mxgraph.aws4.ecs', fillColor: ORANGE },
  'ElasticContainerServiceContainer1': { shapeKey: 'mxgraph.aws4.container_1' },
  'ElasticContainerServiceContainer2': { shapeKey: 'mxgraph.aws4.container_2' },
  'ElasticContainerServiceContainer3': { shapeKey: 'mxgraph.aws4.container_3' },
  'ElasticContainerServiceCopilotCLI': { shapeKey: 'mxgraph.aws4.ecs_copilot_cli' },
  'ElasticContainerServiceECSAnywhere': { shapeKey: 'mxgraph.aws4.ecs_anywhere', fillColor: ORANGE },
  'ElasticContainerServiceService': { shapeKey: 'mxgraph.aws4.ecs_service' },
  'ElasticContainerServiceTask': { shapeKey: 'mxgraph.aws4.ecs_task' },
  'ElasticFabricAdapter': { shapeKey: 'mxgraph.aws4.elastic_fabric_adapter', fillColor: ORANGE },
  'ElasticFileSystemFileSystem': { shapeKey: 'mxgraph.aws4.file_system' },
  'ElasticFileSystemIntelligentTiering': { shapeKey: 'mxgraph.aws4.elastic_file_system_intelligent_tiering' },
  'ElasticFileSystemOneZone': { shapeKey: 'mxgraph.aws4.elastic_file_system_one_zone' },
  'ElasticFileSystemOneZoneInfrequentAccess': { shapeKey: 'mxgraph.aws4.elastic_file_system_one_zone_infrequent_access' },
  'ElasticFileSystemStandard': { shapeKey: 'mxgraph.aws4.elastic_file_system_standard' },
  'ElasticFileSystemStandardInfrequentAccess': { shapeKey: 'mxgraph.aws4.elastic_file_system_infrequent_access' },
  'ElasticLoadBalancing': { shapeKey: 'mxgraph.aws4.elastic_load_balancing', fillColor: PURPLE },
  'ElasticLoadBalancingApplicationLoadBalancer': { shapeKey: 'mxgraph.aws4.application_load_balancer' },
  'ElasticLoadBalancingClassicLoadBalancer': { shapeKey: 'mxgraph.aws4.classic_load_balancer' },
  'ElasticLoadBalancingGatewayLoadBalancer': { shapeKey: 'mxgraph.aws4.gateway_load_balancer' },
  'ElasticLoadBalancingNetworkLoadBalancer': { shapeKey: 'mxgraph.aws4.network_load_balancer' },
  'ElasticTranscoder': { shapeKey: 'mxgraph.aws4.elastic_transcoder', fillColor: ORANGE },
  'ElementalMediaConnect': { shapeKey: 'mxgraph.aws4.elemental_mediaconnect', fillColor: ORANGE },
  'Email': { shapeKey: 'mxgraph.aws4.email_2' },
  'EndUserComputing': { shapeKey: 'mxgraph.aws4.desktop_and_app_streaming', fillColor: TEAL },
  'EventBridge': { shapeKey: 'mxgraph.aws4.eventbridge', fillColor: PINK },
  'EventBridgeCustomEventBus': { shapeKey: 'mxgraph.aws4.eventbridge_custom_event_bus_resource' },
  'EventBridgeDefaultEventBus': { shapeKey: 'mxgraph.aws4.eventbridge_default_event_bus_resource' },
  'EventBridgeEvent': { shapeKey: 'mxgraph.aws4.event' },
  'EventBridgeRule': { shapeKey: 'mxgraph.aws4.rule_3' },
  'EventBridgeSaasPartnerEvent': { shapeKey: 'mxgraph.aws4.eventbridge_saas_partner_event_bus_resource' },
  'EventBridgeSchema': { shapeKey: 'mxgraph.aws4.eventbridge_schema' },
  'EventBridgeSchemaRegistry': { shapeKey: 'mxgraph.aws4.eventbridge_schema_registry' },
  'ExpressWorkflows': { shapeKey: 'mxgraph.aws4.express_workflow', fillColor: PINK },
  'FSx': { shapeKey: 'mxgraph.aws4.fsx', fillColor: GREEN },
  'FaultInjectionSimulator': { shapeKey: 'mxgraph.aws4.fault_injection_simulator', fillColor: PINK },
  'Firewall': { shapeKey: 'mxgraph.aws4.generic_firewall' },
  'Folder': { shapeKey: 'mxgraph.aws4.folder' },
  'Folders': { shapeKey: 'mxgraph.aws4.folders' },
  'Forums': { shapeKey: 'mxgraph.aws4.forums' },
  'FreeRTOS': { shapeKey: 'mxgraph.aws4.iot_thing_freertos_device', fillColor: GREEN },
  'GameLift': { shapeKey: 'mxgraph.aws4.gamelift', fillColor: PURPLE },
  'Gear': { shapeKey: 'mxgraph.aws4.gear' },
  'GenericApplication': { shapeKey: 'mxgraph.aws4.generic_application' },
  'Genericdatabase': { shapeKey: 'mxgraph.aws4.generic_database' },
  'GenomicsCLI': { shapeKey: 'mxgraph.aws4.genomics_cli', fillColor: ORANGE },
  'GitRepository': { shapeKey: 'mxgraph.aws4.git_repository' },
  'Globe': { shapeKey: 'mxgraph.aws4.globe' },
  'Glue': { shapeKey: 'mxgraph.aws4.glue', fillColor: PURPLE },
  'GlueCrawler': { shapeKey: 'mxgraph.aws4.glue_crawlers' },
  'GlueDataBrew': { shapeKey: 'mxgraph.aws4.glue_databrew', fillColor: PURPLE },
  'GlueDataCatalog': { shapeKey: 'mxgraph.aws4.glue_data_catalog' },
  'GlueElasticViews': { shapeKey: 'mxgraph.aws4.glue_elastic_views', fillColor: PURPLE },
  'IAMIdentityCenter': { shapeKey: 'mxgraph.aws4.single_sign_on', fillColor: RED },
  'IdentityAccessManagementAWSSTS': { shapeKey: 'mxgraph.aws4.sts' },
  'IdentityAccessManagementAWSSTSAlternate': { shapeKey: 'mxgraph.aws4.sts_alternate' },
  'IdentityAccessManagementAddon': { shapeKey: 'mxgraph.aws4.addon' },
  'IdentityAccessManagementDataEncryptionKey': { shapeKey: 'mxgraph.aws4.data_encryption_key' },
  'IdentityAccessManagementEncryptedData': { shapeKey: 'mxgraph.aws4.encrypted_data' },
  'IdentityAccessManagementIAMAccessAnalyzer': { shapeKey: 'mxgraph.aws4.access_analyzer' },
  'IdentityAccessManagementIAMRolesAnywhere': { shapeKey: 'mxgraph.aws4.identity_access_management_iam_roles_anywhere' },
  'IdentityAccessManagementLongTermSecurityCredential': { shapeKey: 'mxgraph.aws4.long_term_security_credential' },
  'IdentityAccessManagementMFAToken': { shapeKey: 'mxgraph.aws4.mfa_token' },
  'IdentityAccessManagementPermissions': { shapeKey: 'mxgraph.aws4.permissions' },
  'IdentityAccessManagementRole': { shapeKey: 'mxgraph.aws4.role' },
  'IdentityAccessManagementTemporarySecurityCredential': { shapeKey: 'mxgraph.aws4.temporary_security_credential' },
  'IdentityandAccessManagement': { shapeKey: 'mxgraph.aws4.identity_and_access_management', fillColor: RED },
  'Inspector': { shapeKey: 'mxgraph.aws4.inspector', fillColor: RED },
  'InspectorAgent': { shapeKey: 'mxgraph.aws4.agent' },
  'Internet': { shapeKey: 'mxgraph.aws4.internet' },
  'InternetOfThings': { shapeKey: 'mxgraph.aws4.internet_of_things', fillColor: GREEN },
  'Internetalt1': { shapeKey: 'mxgraph.aws4.internet_alt1' },
  'Internetalt2': { shapeKey: 'mxgraph.aws4.internet_alt2' },
  'IoT1Click': { shapeKey: 'mxgraph.aws4.iot_1click', fillColor: GREEN },
  'IoTAction': { shapeKey: 'mxgraph.aws4.action' },
  'IoTActuator': { shapeKey: 'mxgraph.aws4.actuator' },
  'IoTAlexaEnabledDevice': { shapeKey: 'mxgraph.aws4.alexa_skill' },
  'IoTAlexaSkill': { shapeKey: 'mxgraph.aws4.alexa_skill' },
  'IoTAlexaVoiceService': { shapeKey: 'mxgraph.aws4.alexa_enabled_device' },
  'IoTAnalytics': { shapeKey: 'mxgraph.aws4.iot_analytics', fillColor: GREEN },
  'IoTAnalyticsChannel': { shapeKey: 'mxgraph.aws4.iot_analytics_channel' },
  'IoTAnalyticsDataStore': { shapeKey: 'mxgraph.aws4.iot_analytics_data_store' },
  'IoTAnalyticsDataset': { shapeKey: 'mxgraph.aws4.data_set' },
  'IoTAnalyticsNotebook': { shapeKey: 'mxgraph.aws4.notebook' },
  'IoTAnalyticsPipeline': { shapeKey: 'mxgraph.aws4.iot_analytics_pipeline' },
  'IoTButton': { shapeKey: 'mxgraph.aws4.iot_button', fillColor: GREEN },
  'IoTCertificate': { shapeKey: 'mxgraph.aws4.certificate_manager', strokeColor: GREEN },
  'IoTCore': { shapeKey: 'mxgraph.aws4.iot_core', fillColor: GREEN },
  'IoTDesiredState': { shapeKey: 'mxgraph.aws4.desired_state' },
  'IoTDeviceDefender': { shapeKey: 'mxgraph.aws4.iot_device_defender', fillColor: GREEN },
  'IoTDeviceDefenderIoTDeviceJobs': { shapeKey: 'mxgraph.aws4.iot_device_defender_iot_device_jobs', strokeColor: GREEN },
  'IoTDeviceGateway': { shapeKey: 'mxgraph.aws4.iot_device_gateway' },
  'IoTDeviceManagement': { shapeKey: 'mxgraph.aws4.iot_device_management', fillColor: GREEN },
  'IoTDeviceManagementFleetHub': { shapeKey: 'mxgraph.aws4.iot_device_management_fleet' },
  'IoTEcho': { shapeKey: 'mxgraph.aws4.echo' },
  'IoTEduKit': { shapeKey: 'mxgraph.aws4.iot_edukit', fillColor: GREEN },
  'IoTEvents': { shapeKey: 'mxgraph.aws4.iot_events', fillColor: GREEN },
  'IoTExpressLink': { shapeKey: 'mxgraph.aws4.iot_expresslink', fillColor: GREEN },
  'IoTFireTV': { shapeKey: 'mxgraph.aws4.firetv', strokeColor: GREEN },
  'IoTFireTVStick': { shapeKey: 'mxgraph.aws4.firetv_stick', strokeColor: GREEN },
  'IoTFleetWise': { shapeKey: 'mxgraph.aws4.iot_fleetwise', fillColor: GREEN },
  'IoTGreengrass': { shapeKey: 'mxgraph.aws4.greengrass', fillColor: GREEN },
  'IoTGreengrassArtifact': { shapeKey: 'mxgraph.aws4.iot_greengrass_artifact' },
  'IoTGreengrassComponent': { shapeKey: 'mxgraph.aws4.iot_greengrass_component' },
  'IoTGreengrassComponentMachineLearning': { shapeKey: 'mxgraph.aws4.iot_greengrass_component_machine_learning' },
  'IoTGreengrassComponentNucleus': { shapeKey: 'mxgraph.aws4.iot_greengrass_component_nucleus' },
  'IoTGreengrassComponentPrivate': { shapeKey: 'mxgraph.aws4.iot_greengrass_component_private' },
  'IoTGreengrassComponentPublic': { shapeKey: 'mxgraph.aws4.iot_greengrass_component_public' },
  'IoTGreengrassConnector': { shapeKey: 'mxgraph.aws4.connector', strokeColor: GREEN },
  'IoTGreengrassInterprocessCommunication': { shapeKey: 'mxgraph.aws4.iot_greengrass_interprocess_communication' },
  'IoTGreengrassProtocol': { shapeKey: 'mxgraph.aws4.iot_greengrass_protocol' },
  'IoTGreengrassRecipe': { shapeKey: 'mxgraph.aws4.iot_greengrass_recipe' },
  'IoTGreengrassStreamManager': { shapeKey: 'mxgraph.aws4.iot_greengrass_stream_manager' },
  'IoTHTTP2Protocol': { shapeKey: 'mxgraph.aws4.http2_protocol' },
  'IoTHTTPProtocol': { shapeKey: 'mxgraph.aws4.http_protocol' },
  'IoTHardwareBoard': { shapeKey: 'mxgraph.aws4.hardware_board' },
  'IoTLambdaFunction': { shapeKey: 'mxgraph.aws4.lambda_function', strokeColor: GREEN },
  'IoTLoRaWANProtocol': { shapeKey: 'mxgraph.aws4.iot_lorawan_protocol' },
  'IoTMQTTProtocol': { shapeKey: 'mxgraph.aws4.mqtt_protocol' },
  'IoTOverAirUpdate': { shapeKey: 'mxgraph.aws4.iot_over_the_air_update' },
  'IoTPolicy': { shapeKey: 'mxgraph.aws4.policy' },
  'IoTReportedState': { shapeKey: 'mxgraph.aws4.reported_state' },
  'IoTRoboRunner': { shapeKey: 'mxgraph.aws4.iot_roborunner', fillColor: GREEN },
  'IoTRule': { shapeKey: 'mxgraph.aws4.rule' },
  'IoTSailboat': { shapeKey: 'mxgraph.aws4.iot_sailboat' },
  'IoTSensor': { shapeKey: 'mxgraph.aws4.sensor' },
  'IoTServo': { shapeKey: 'mxgraph.aws4.servo' },
  'IoTShadow': { shapeKey: 'mxgraph.aws4.shadow' },
  'IoTSimulator': { shapeKey: 'mxgraph.aws4.simulator' },
  'IoTSiteWise': { shapeKey: 'mxgraph.aws4.iot_sitewise', fillColor: GREEN },
  'IoTSiteWiseAsset': { shapeKey: 'mxgraph.aws4.iot_sitewise_asset' },
  'IoTSiteWiseAssetHierarchy': { shapeKey: 'mxgraph.aws4.iot_sitewise_asset_hierarchy' },
  'IoTSiteWiseAssetModel': { shapeKey: 'mxgraph.aws4.iot_sitewise_asset_model' },
  'IoTSiteWiseAssetProperties': { shapeKey: 'mxgraph.aws4.iot_sitewise_asset_properties' },
  'IoTSiteWiseDataStreams': { shapeKey: 'mxgraph.aws4.iot_sitewise_data_streams' },
  'IoTThingBank': { shapeKey: 'mxgraph.aws4.bank' },
  'IoTThingBicycle': { shapeKey: 'mxgraph.aws4.bycicle', strokeColor: GREEN },
  'IoTThingCamera': { shapeKey: 'mxgraph.aws4.camera' },
  'IoTThingCar': { shapeKey: 'mxgraph.aws4.car' },
  'IoTThingCart': { shapeKey: 'mxgraph.aws4.cart' },
  'IoTThingCoffeePot': { shapeKey: 'mxgraph.aws4.coffee_pot' },
  'IoTThingDoorLock': { shapeKey: 'mxgraph.aws4.door_lock' },
  'IoTThingFactory': { shapeKey: 'mxgraph.aws4.factory' },
  'IoTThingFreeRTOSDevice': { shapeKey: 'mxgraph.aws4.iot_thing_freertos_device' },
  'IoTThingGeneric': { shapeKey: 'mxgraph.aws4.generic' },
  'IoTThingHouse': { shapeKey: 'mxgraph.aws4.house' },
  'IoTThingHumiditySensor': { shapeKey: 'mxgraph.aws4.iot_thing_humidity_sensor' },
  'IoTThingIndustrialPC': { shapeKey: 'mxgraph.aws4.iot_thing_industrial_pc' },
  'IoTThingLightbulb': { shapeKey: 'mxgraph.aws4.lightbulb' },
  'IoTThingMedicalEmergency': { shapeKey: 'mxgraph.aws4.medical_emergency' },
  'IoTThingPLC': { shapeKey: 'mxgraph.aws4.iot_thing_plc' },
  'IoTThingPoliceEmergency': { shapeKey: 'mxgraph.aws4.police_emergency' },
  'IoTThingRelay': { shapeKey: 'mxgraph.aws4.iot_thing_relay' },
  'IoTThingStacklight': { shapeKey: 'mxgraph.aws4.iot_thing_stacklight' },
  'IoTThingTemperatureHumiditySensor': { shapeKey: 'mxgraph.aws4.iot_thing_temperature_humidity_sensor' },
  'IoTThingTemperatureSensor': { shapeKey: 'mxgraph.aws4.iot_thing_temperature_sensor' },
  'IoTThingTemperatureVibrationSensor': { shapeKey: 'mxgraph.aws4.iot_thing_temperature_vibration_sensor' },
  'IoTThingThermostat': { shapeKey: 'mxgraph.aws4.thermostat' },
  'IoTThingTravel': { shapeKey: 'mxgraph.aws4.travel' },
  'IoTThingUtility': { shapeKey: 'mxgraph.aws4.utility' },
  'IoTThingVibrationSensor': { shapeKey: 'mxgraph.aws4.iot_thing_vibration_sensor' },
  'IoTThingWindfarm': { shapeKey: 'mxgraph.aws4.windfarm' },
  'IoTThingsGraph': { shapeKey: 'mxgraph.aws4.iot_things_graph', fillColor: GREEN },
  'IoTTopic': { shapeKey: 'mxgraph.aws4.topic_2' },
  'IoTTwinMaker': { shapeKey: 'mxgraph.aws4.iot_twinmaker', fillColor: GREEN },
  'KeyManagementService': { shapeKey: 'mxgraph.aws4.key_management_service', fillColor: RED },
  'Kinesis': { shapeKey: 'mxgraph.aws4.kinesis', fillColor: PURPLE },
  'KinesisDataAnalytics': { shapeKey: 'mxgraph.aws4.kinesis_data_analytics', fillColor: PURPLE },
  'KinesisDataStreams': { shapeKey: 'mxgraph.aws4.kinesis_data_streams', fillColor: PURPLE },
  'KinesisFirehose': { shapeKey: 'mxgraph.aws4.kinesis_data_firehose', fillColor: PURPLE },
  'KinesisVideoStreams': { shapeKey: 'mxgraph.aws4.kinesis_video_streams', fillColor: PURPLE },
  'KinesisVideoStreams2': { shapeKey: 'mxgraph.aws4.kinesis_video_streams', fillColor: ORANGE },
  'Lambda': { shapeKey: 'mxgraph.aws4.lambda', fillColor: ORANGE },
  'LambdaLambdaFunction': { shapeKey: 'mxgraph.aws4.lambda_function' },
  'Lex': { shapeKey: 'mxgraph.aws4.lex', fillColor: TEAL },
  'LicenseManager': { shapeKey: 'mxgraph.aws4.license_manager', fillColor: PINK },
  'LicenseManagerApplicationDiscovery': { shapeKey: 'mxgraph.aws4.license_manager_application_discovery' },
  'LicenseManagerLicenseBlending': { shapeKey: 'mxgraph.aws4.license_manager_license_blending' },
  'Lightsail': { shapeKey: 'mxgraph.aws4.lightsail', fillColor: ORANGE },
  'LocationService': { shapeKey: 'mxgraph.aws4.location_service', fillColor: RED },
  'LocationServiceGeofence': { shapeKey: 'mxgraph.aws4.location_service_geofence' },
  'LocationServiceMap': { shapeKey: 'mxgraph.aws4.location_service_map' },
  'LocationServicePlace': { shapeKey: 'mxgraph.aws4.location_service_place' },
  'LocationServiceRoutes': { shapeKey: 'mxgraph.aws4.location_service_routes' },
  'LocationServiceTrack': { shapeKey: 'mxgraph.aws4.location_service_track' },
  'LookoutforMetrics': { shapeKey: 'mxgraph.aws4.lookout_for_metrics', fillColor: TEAL },
  'MQBroker': { shapeKey: 'mxgraph.aws4.mq_broker' },
  'MSKAmazonMSKConnect': { shapeKey: 'mxgraph.aws4.msk_amazon_msk_connect' },
  'MachineLearning': { shapeKey: 'mxgraph.aws4.machine_learning', fillColor: TEAL },
  'Macie': { shapeKey: 'mxgraph.aws4.macie', fillColor: RED },
  'MagnifyingGlass': { shapeKey: 'mxgraph.aws4.magnifying_glass_2' },
  'MainframeModernization': { shapeKey: 'mxgraph.aws4.mainframe_modernization', fillColor: TEAL },
  'MainframeModernizationAnalyzer': { shapeKey: 'mxgraph.aws4.mainframe_modernization_analyzer' },
  'MainframeModernizationCompiler': { shapeKey: 'mxgraph.aws4.mainframe_modernization_compiler' },
  'MainframeModernizationConverter': { shapeKey: 'mxgraph.aws4.mainframe_modernization_converter' },
  'MainframeModernizationDeveloper': { shapeKey: 'mxgraph.aws4.mainframe_modernization_developer' },
  'MainframeModernizationRuntime': { shapeKey: 'mxgraph.aws4.mainframe_modernization_runtime' },
  'ManagedBlockchain': { shapeKey: 'mxgraph.aws4.managed_blockchain', fillColor: ORANGE },
  'ManagedBlockchainBlockchain': { shapeKey: 'mxgraph.aws4.blockchain_resource' },
  'ManagedGrafana': { shapeKey: 'mxgraph.aws4.managed_service_for_grafana', fillColor: PINK },
  'ManagedServiceforPrometheus': { shapeKey: 'mxgraph.aws4.managed_service_for_prometheus', fillColor: PINK },
  'ManagedServices': { shapeKey: 'mxgraph.aws4.managed_services', fillColor: BLUE },
  'ManagedStreamingforApacheKafka': { shapeKey: 'mxgraph.aws4.managed_streaming_for_kafka', fillColor: PURPLE },
  'ManagedWorkflowsforApacheAirflow': { shapeKey: 'mxgraph.aws4.managed_workflows_for_apache_airflow', fillColor: PINK },
  'ManagementConsole': { shapeKey: 'mxgraph.aws4.management_console', fillColor: PINK },
  'MarketplaceDark': { shapeKey: 'mxgraph.aws4.marketplace', strokeColor: DARK },
  'MarketplaceLight': { shapeKey: 'mxgraph.aws4.marketplace', fillColor: DARK },
  'MediaServices': { shapeKey: 'mxgraph.aws4.media_services', fillColor: ORANGE },
  'MemoryDBforRedis': { shapeKey: 'mxgraph.aws4.memorydb_for_redis', fillColor: BLUE },
  'MigrationEvaluator': { shapeKey: 'mxgraph.aws4.migration_evaluator', fillColor: TEAL },
  'MigrationHub': { shapeKey: 'mxgraph.aws4.migration_hub', fillColor: TEAL },
  'MigrationHubRefactorSpacesApplications': { shapeKey: 'mxgraph.aws4.migration_hub_refactor_spaces_applications' },
  'MigrationHubRefactorSpacesEnvironments': { shapeKey: 'mxgraph.aws4.migration_hub_refactor_spaces_environments' },
  'MigrationHubRefactorSpacesServices': { shapeKey: 'mxgraph.aws4.migration_hub_refactor_spaces_services' },
  'Mobileclient': { shapeKey: 'mxgraph.aws4.mobile_client' },
  'Multimedia': { shapeKey: 'mxgraph.aws4.multimedia' },
  'NetworkFirewall': { shapeKey: 'mxgraph.aws4.network_firewall', fillColor: RED },
  'NetworkFirewallEndpoints': { shapeKey: 'mxgraph.aws4.network_firewall_endpoints' },
  'Officebuilding': { shapeKey: 'mxgraph.aws4.office_building' },
  'OpenSearchService': { shapeKey: 'mxgraph.aws4.elasticsearch_service', fillColor: PURPLE },
  'OpsWorks': { shapeKey: 'mxgraph.aws4.opsworks', fillColor: PINK },
  'OpsWorksApps': { shapeKey: 'mxgraph.aws4.opsworks_apps' },
  'OpsWorksDeployments': { shapeKey: 'mxgraph.aws4.deployments' },
  'OpsWorksInstances': { shapeKey: 'mxgraph.aws4.instances_2' },
  'OpsWorksLayers': { shapeKey: 'mxgraph.aws4.layers' },
  'OpsWorksMonitoring': { shapeKey: 'mxgraph.aws4.monitoring' },
  'OpsWorksPermissions': { shapeKey: 'mxgraph.aws4.opsworks_permissions' },
  'OpsWorksResources': { shapeKey: 'mxgraph.aws4.resources' },
  'OpsWorksStack2': { shapeKey: 'mxgraph.aws4.stack2' },
  'Organizations': { shapeKey: 'mxgraph.aws4.organizations', fillColor: RED },
  'OrganizationsAccount': { shapeKey: 'mxgraph.aws4.organizations_account2' },
  'OrganizationsManagementAccount': { shapeKey: 'mxgraph.aws4.organizations_management_account2' },
  'OrganizationsOrganizationalUnit': { shapeKey: 'mxgraph.aws4.organizations_organizational_unit2' },
  'Outpostsrack': { shapeKey: 'mxgraph.aws4.outposts', fillColor: ORANGE },
  'Outpostsservers': { shapeKey: 'mxgraph.aws4.outposts_1u_and_2u_servers', fillColor: ORANGE },
  'ParallelCluster': { shapeKey: 'mxgraph.aws4.parallel_cluster', fillColor: ORANGE },
  'Pinpoint': { shapeKey: 'mxgraph.aws4.pinpoint', fillColor: RED },
  'PinpointAPIs': { shapeKey: 'mxgraph.aws4.pinpoint', fillColor: RED },
  'PinpointJourney': { shapeKey: 'mxgraph.aws4.pinpoint_journey' },
  'Polly': { shapeKey: 'mxgraph.aws4.polly', fillColor: TEAL },
  'Question': { shapeKey: 'mxgraph.aws4.question' },
  'QuickSight': { shapeKey: 'mxgraph.aws4.quicksight', fillColor: PURPLE },
  'RDS': { shapeKey: 'mxgraph.aws4.rds', fillColor: BLUE },
  'RDSMultiAZ': { shapeKey: 'mxgraph.aws4.rds_multi_az', strokeColor: BLUE },
  'RDSMultiAZDBCluster': { shapeKey: 'mxgraph.aws4.rds_multi_az_db_cluster', strokeColor: BLUE },
  'RDSProxyInstance': { shapeKey: 'mxgraph.aws4.rds_proxy', strokeColor: BLUE },
  'RDSProxyInstanceAlternate': { shapeKey: 'mxgraph.aws4.rds_proxy_alt', strokeColor: BLUE },
  'RDSonVMware': { shapeKey: 'mxgraph.aws4.rds', fillColor: BLUE },
  'Recover': { shapeKey: 'mxgraph.aws4.recover' },
  'Redshift': { shapeKey: 'mxgraph.aws4.redshift', fillColor: PURPLE },
  'RedshiftDenseComputeNode': { shapeKey: 'mxgraph.aws4.dense_compute_node' },
  'RedshiftDenseStorageNode': { shapeKey: 'mxgraph.aws4.dense_storage_node' },
  'RedshiftML': { shapeKey: 'mxgraph.aws4.redshift_ml' },
  'RedshiftRA3': { shapeKey: 'mxgraph.aws4.redshift_ra3' },
  'Region': { shapeKey: 'mxgraph.aws4.group_region', strokeColor: CYAN },
  'Rekognition': { shapeKey: 'mxgraph.aws4.rekognition_2', fillColor: TEAL },
  'RekognitionImage': { shapeKey: 'mxgraph.aws4.rekognition_image' },
  'RekognitionVideo': { shapeKey: 'mxgraph.aws4.rekognition_video' },
  'ReservedInstanceReporting': { shapeKey: 'mxgraph.aws4.reserved_instance_reporting', fillColor: GREEN },
  'ResourceAccessManager': { shapeKey: 'mxgraph.aws4.resource_access_manager', fillColor: RED },
  'RoboMakerCloudExtensionsROS': { shapeKey: 'mxgraph.aws4.cloud_extension_ros' },
  'RoboMakerDevelopmentEnvironment': { shapeKey: 'mxgraph.aws4.development_environment' },
  'RoboMakerFleetManagement': { shapeKey: 'mxgraph.aws4.fleet_management' },
  'RoboMakerSimulation': { shapeKey: 'mxgraph.aws4.simulation' },
  'Route53': { shapeKey: 'mxgraph.aws4.route_53', fillColor: PURPLE },
  'Route53ApplicationRecoveryController': { shapeKey: 'mxgraph.aws4.route_53_application_recovery_controller' },
  'Route53HostedZone': { shapeKey: 'mxgraph.aws4.hosted_zone' },
  'Route53ReadinessChecks': { shapeKey: 'mxgraph.aws4.route_53_readiness_checks' },
  'Route53Resolver': { shapeKey: 'mxgraph.aws4.route_53_resolver' },
  'Route53ResolverDNSFirewall': { shapeKey: 'mxgraph.aws4.route_53_resolver_dns_firewall' },
  'Route53ResolverQueryLogging': { shapeKey: 'mxgraph.aws4.route_53_resolver_query_logging' },
  'Route53RouteTable': { shapeKey: 'mxgraph.aws4.route_table' },
  'Route53RoutingControls': { shapeKey: 'mxgraph.aws4.route_53_routing_controls' },
  'S3onOutposts': { shapeKey: 'mxgraph.aws4.s3_on_outposts_storage', fillColor: GREEN },
  'SAMLtoken': { shapeKey: 'mxgraph.aws4.saml_token' },
  'SDK': { shapeKey: 'mxgraph.aws4.external_sdk' },
  'SSLpadlock': { shapeKey: 'mxgraph.aws4.ssl_padlock' },
  'SageMaker': { shapeKey: 'mxgraph.aws4.sagemaker_model', fillColor: TEAL },
  'SageMakerCanvas': { shapeKey: 'mxgraph.aws4.sagemaker_canvas' },
  'SageMakerModel': { shapeKey: 'mxgraph.aws4.sagemaker_model' },
  'SageMakerNotebook': { shapeKey: 'mxgraph.aws4.sagemaker_notebook' },
  'SageMakerTrain': { shapeKey: 'mxgraph.aws4.sagemaker_train' },
  'SecretsManager': { shapeKey: 'mxgraph.aws4.secrets_manager', fillColor: RED },
  'SecurityHubFinding': { shapeKey: 'mxgraph.aws4.security_hub_finding', strokeColor: RED },
  'ServerMigrationService': { shapeKey: 'mxgraph.aws4.server_migration_service', fillColor: TEAL },
  'ServerlessApplicationRepository': { shapeKey: 'mxgraph.aws4.serverless_application_repository', fillColor: ORANGE },
  'Servers': { shapeKey: 'mxgraph.aws4.servers' },
  'ServiceCatalog': { shapeKey: 'mxgraph.aws4.service_catalog', fillColor: PINK },
  'Shield': { shapeKey: 'mxgraph.aws4.shield', fillColor: RED },
  'Shield2': { shapeKey: 'mxgraph.aws4.shield2' },
  'ShieldAWSShieldAdvanced': { shapeKey: 'mxgraph.aws4.shield_shield_advanced' },
  'SimpleEmailService': { shapeKey: 'mxgraph.aws4.simple_email_service', fillColor: RED },
  'SimpleEmailServiceEmail': { shapeKey: 'mxgraph.aws4.email' },
  'SimpleNotificationService': { shapeKey: 'mxgraph.aws4.sns', fillColor: PINK },
  'SimpleNotificationServiceEmailNotification': { shapeKey: 'mxgraph.aws4.email_notification' },
  'SimpleNotificationServiceHTTPNotification': { shapeKey: 'mxgraph.aws4.http_notification' },
  'SimpleNotificationServiceTopic': { shapeKey: 'mxgraph.aws4.topic' },
  'SimpleQueueService': { shapeKey: 'mxgraph.aws4.sqs', fillColor: PINK },
  'SimpleQueueServiceMessage': { shapeKey: 'mxgraph.aws4.message' },
  'SimpleQueueServiceQueue': { shapeKey: 'mxgraph.aws4.queue' },
  'SimpleStorageService': { shapeKey: 'mxgraph.aws4.s3', fillColor: GREEN },
  'SimpleStorageServiceBucket': { shapeKey: 'mxgraph.aws4.s3', strokeColor: GREEN },
  'SimpleStorageServiceBucketWithObjects': { shapeKey: 'mxgraph.aws4.bucket_with_objects' },
  'SimpleStorageServiceGeneralAccessPoints': { shapeKey: 'mxgraph.aws4.general_access_points' },
  'SimpleStorageServiceGlacier': { shapeKey: 'mxgraph.aws4.glacier', fillColor: GREEN },
  'SimpleStorageServiceGlacierArchive': { shapeKey: 'mxgraph.aws4.vault' },
  'SimpleStorageServiceGlacierVault': { shapeKey: 'mxgraph.aws4.archive' },
  'SimpleStorageServiceObject': { shapeKey: 'mxgraph.aws4.object' },
  'SimpleStorageServiceS3GlacierDeepArchive': { shapeKey: 'mxgraph.aws4.glacier_deep_archive' },
  'SimpleStorageServiceS3GlacierFlexibleRetrieval': { shapeKey: 'mxgraph.aws4.glacier' },
  'SimpleStorageServiceS3GlacierInstantRetrieval': { shapeKey: 'mxgraph.aws4.simple_storage_service_s3_glacier_instant_retrieval' },
  'SimpleStorageServiceS3IntelligentTiering': { shapeKey: 'mxgraph.aws4.intelligent_tiering' },
  'SimpleStorageServiceS3ObjectLambda': { shapeKey: 'mxgraph.aws4.s3_object_lambda' },
  'SimpleStorageServiceS3ObjectLambdaAccessPoints': { shapeKey: 'mxgraph.aws4.s3_object_lambda_access_points' },
  'SimpleStorageServiceS3OnOutposts': { shapeKey: 'mxgraph.aws4.s3_on_outposts' },
  'SimpleStorageServiceS3OneZoneIA': { shapeKey: 'mxgraph.aws4.one_zone_ia' },
  'SimpleStorageServiceS3Replication': { shapeKey: 'mxgraph.aws4.replication' },
  'SimpleStorageServiceS3ReplicationTimeControl': { shapeKey: 'mxgraph.aws4.replication_time_control' },
  'SimpleStorageServiceS3Standard': { shapeKey: 'mxgraph.aws4.s3', strokeColor: GREEN },
  'SimpleStorageServiceS3StandardIA': { shapeKey: 'mxgraph.aws4.standard_ia' },
  'SimpleStorageServiceS3StorageLens': { shapeKey: 'mxgraph.aws4.s3_storage_lens' },
  'SimpleStorageServiceVPCAccessPoints': { shapeKey: 'mxgraph.aws4.vpc_access_points' },
  'Snowball': { shapeKey: 'mxgraph.aws4.snowball', fillColor: GREEN },
  'SnowballEdge': { shapeKey: 'mxgraph.aws4.snowball_edge', fillColor: GREEN },
  'SnowballSnowballImportExport': { shapeKey: 'mxgraph.aws4.import_export' },
  'SourceCode': { shapeKey: 'mxgraph.aws4.source_code' },
  'StepFunction': { shapeKey: 'mxgraph.aws4.step_functions', fillColor: PINK },
  'StepFunctions': { shapeKey: 'mxgraph.aws4.step_functions', fillColor: PINK },
  'StorageGateway': { shapeKey: 'mxgraph.aws4.storage_gateway', fillColor: GREEN },
  'StorageGatewayAmazonFSxFileGateway': { shapeKey: 'mxgraph.aws4.fsx_file_gateway' },
  'StorageGatewayAmazonS3FileGateway': { shapeKey: 'mxgraph.aws4.s3_file_gateway' },
  'StorageGatewayCachedVolume': { shapeKey: 'mxgraph.aws4.cached_volume' },
  'StorageGatewayFileGateway': { shapeKey: 'mxgraph.aws4.file_gateway' },
  'StorageGatewayNoncachedVolume': { shapeKey: 'mxgraph.aws4.non_cached_volume' },
  'StorageGatewayTapeGateway': { shapeKey: 'mxgraph.aws4.tape_gateway' },
  'StorageGatewayVirtualTapeLibrary': { shapeKey: 'mxgraph.aws4.virtual_tape_library' },
  'StorageGatewayVolumeGateway': { shapeKey: 'mxgraph.aws4.volume_gateway' },
  'Support': { shapeKey: 'mxgraph.aws4.support', fillColor: BLUE },
  'SystemsManager': { shapeKey: 'mxgraph.aws4.systems_manager', fillColor: PINK },
  'SystemsManagerAutomation': { shapeKey: 'mxgraph.aws4.automation' },
  'SystemsManagerChangeCalendar': { shapeKey: 'mxgraph.aws4.systems_manager_change_calendar' },
  'SystemsManagerChangeManager': { shapeKey: 'mxgraph.aws4.systems_manager_change_manager' },
  'SystemsManagerCompliance': { shapeKey: 'mxgraph.aws4.systems_manager_compliance' },
  'SystemsManagerDocuments': { shapeKey: 'mxgraph.aws4.documents', fillColor: PINK },
  'SystemsManagerIncidentManager': { shapeKey: 'mxgraph.aws4.systems_manager_incident_manager', fillColor: PINK },
  'SystemsManagerInventory': { shapeKey: 'mxgraph.aws4.inventory' },
  'SystemsManagerMaintenanceWindows': { shapeKey: 'mxgraph.aws4.maintenance_windows' },
  'SystemsManagerOpsCenter': { shapeKey: 'mxgraph.aws4.systems_manager_opscenter' },
  'SystemsManagerParameterStore': { shapeKey: 'mxgraph.aws4.parameter_store' },
  'SystemsManagerPatchManager': { shapeKey: 'mxgraph.aws4.patch_manager' },
  'SystemsManagerRunCommand': { shapeKey: 'mxgraph.aws4.run_command' },
  'SystemsManagerSessionManager': { shapeKey: 'mxgraph.aws4.systems_manager_session_manager' },
  'SystemsManagerStateManager': { shapeKey: 'mxgraph.aws4.state_manager' },
  'Tapestorage': { shapeKey: 'mxgraph.aws4.tape_storage' },
  'Textract': { shapeKey: 'mxgraph.aws4.textract', fillColor: TEAL },
  'ThinkboxXMesh': { shapeKey: 'mxgraph.aws4.thinkbox_xmesh', fillColor: ORANGE },
  'Toolkit': { shapeKey: 'mxgraph.aws4.external_toolkit' },
  'Traditionalserver': { shapeKey: 'mxgraph.aws4.traditional_server' },
  'TransferFamily': { shapeKey: 'mxgraph.aws4.transfer_family', fillColor: TEAL },
  'TransferFamilyAWSFTP': { shapeKey: 'mxgraph.aws4.transfer_for_ftp_resource' },
  'TransferFamilyAWSFTPS': { shapeKey: 'mxgraph.aws4.transfer_for_ftps_resource' },
  'TransferFamilyAWSSFTP': { shapeKey: 'mxgraph.aws4.transfer_for_sftp_resource' },
  'TransitGateway': { shapeKey: 'mxgraph.aws4.transit_gateway', fillColor: PURPLE },
  'TransitGatewayAttachment': { shapeKey: 'mxgraph.aws4.transit_gateway_attachment' },
  'TrustedAdvisor': { shapeKey: 'mxgraph.aws4.trusted_advisor', fillColor: PINK },
  'TrustedAdvisorChecklist': { shapeKey: 'mxgraph.aws4.checklist' },
  'TrustedAdvisorChecklistCost': { shapeKey: 'mxgraph.aws4.checklist_cost' },
  'TrustedAdvisorChecklistFaultTolerant': { shapeKey: 'mxgraph.aws4.checklist_fault_tolerant' },
  'TrustedAdvisorChecklistPerformance': { shapeKey: 'mxgraph.aws4.checklist_performance' },
  'TrustedAdvisorChecklistSecurity': { shapeKey: 'mxgraph.aws4.checklist_security' },
  'User': { shapeKey: 'mxgraph.aws4.user' },
  'Users': { shapeKey: 'mxgraph.aws4.users' },
  'VPCCarrierGateway': { shapeKey: 'mxgraph.aws4.vpc_carrier_gateway' },
  'VPCCustomerGateway': { shapeKey: 'mxgraph.aws4.customer_gateway' },
  'VPCElasticNetworkAdapter': { shapeKey: 'mxgraph.aws4.elastic_network_adapter' },
  'VPCElasticNetworkInterface': { shapeKey: 'mxgraph.aws4.elastic_network_interface' },
  'VPCEndpoints': { shapeKey: 'mxgraph.aws4.endpoints' },
  'VPCFlowLogs': { shapeKey: 'mxgraph.aws4.flow_logs' },
  'VPCInternetGateway': { shapeKey: 'mxgraph.aws4.internet_gateway' },
  'VPCNATGateway': { shapeKey: 'mxgraph.aws4.nat_gateway' },
  'VPCNetworkAccessAnalyzer': { shapeKey: 'mxgraph.aws4.vpc_network_access_analyzer' },
  'VPCNetworkAccessControlList': { shapeKey: 'mxgraph.aws4.network_access_control_list' },
  'VPCPeeringConnection': { shapeKey: 'mxgraph.aws4.peering' },
  'VPCReachabilityAnalyzer': { shapeKey: 'mxgraph.aws4.vpc_reachability_analyzer' },
  'VPCRouter': { shapeKey: 'mxgraph.aws4.router' },
  'VPCSubnetPrivate': { shapeKey: 'mxgraph.aws4.opsworks_permissions', fillColor: CYAN },
  'VPCSubnetPublic': { shapeKey: 'mxgraph.aws4.opsworks_permissions', fillColor: GREEN },
  'VPCTrafficMirroring': { shapeKey: 'mxgraph.aws4.vpc_traffic_mirroring' },
  'VPCVPNConnection': { shapeKey: 'mxgraph.aws4.vpn_connection' },
  'VPCVPNGateway': { shapeKey: 'mxgraph.aws4.vpn_gateway' },
  'VirtualPrivateCloud': { shapeKey: 'mxgraph.aws4.vpc_virtual_private_cloud_vpc', fillColor: PURPLE },
  'VirtualPrivateCloudVPC': { shapeKey: 'mxgraph.aws4.group_vpc', strokeColor: GREEN },
  'WAF': { shapeKey: 'mxgraph.aws4.waf', fillColor: RED },
  'WAFBadBot': { shapeKey: 'mxgraph.aws4.waf_bad_bot' },
  'WAFBot': { shapeKey: 'mxgraph.aws4.waf_bot' },
  'WAFBotControl': { shapeKey: 'mxgraph.aws4.waf_bot_control' },
  'WAFFilteringRule': { shapeKey: 'mxgraph.aws4.filtering_rule' },
  'WAFLabels': { shapeKey: 'mxgraph.aws4.waf_labels' },
  'WAFManagedRule': { shapeKey: 'mxgraph.aws4.waf_managed_rule' },
  'WAFRule': { shapeKey: 'mxgraph.aws4.waf_rule' },
  'WorkDocs': { shapeKey: 'mxgraph.aws4.workdocs', fillColor: RED },
  'WorkDocsSDK': { shapeKey: 'mxgraph.aws4.workdocs', fillColor: RED },
  'WorkMail': { shapeKey: 'mxgraph.aws4.workmail', fillColor: RED },
  'WorkSpaces': { shapeKey: 'mxgraph.aws4.workspaces', fillColor: TEAL },
  'WorkSpacesWeb': { shapeKey: 'mxgraph.aws4.workspaces', fillColor: TEAL },
  'XRay': { shapeKey: 'mxgraph.aws4.xray', fillColor: BLUE },
};

// Sprites that exist in awslib but have no confirmed mxgraph shape
const AWSLIB_UNKNOWN = new Set<string>([
  'Activate',
  'ApacheMXNetonAWS',
  'AppFlow',
  'AppRunner',
  'AugmentedAIA2I',
  'BackupAWSBackupsupportforVMwareWorkloads',
  'BillingConductor',
  'Bottlerocket',
  'Budgets',
  'CloudControlAPI',
  'CloudDevelopmentKit',
  'CloudFinancialManagement',
  'CloudMap',
  'CloudMapService',
  'CloudShell',
  'Cloudalt',
  'CodeGuru',
  'CodeWhisperer',
  'CommandLineInterface',
  'Comprehend',
  'ComprehendMedical',
  'ComputeOptimizer',
  'Containers',
  'ControlTower',
  'Corretto',
  'CostExplorer',
  'CostandUsageReport',
  'CustomerEnablement',
  'DataExchangeforAPIs',
  'DeepComposer',
  'DeepLearningContainers',
  'DeepLens',
  'DeepRacer',
  'Detective',
  'DeveloperTools',
  'DistroforOpenTelemetry',
  'EKSAnywhere',
  'EKSCloud',
  'EKSDistro',
  'ElasticInference',
  'ElasticKubernetesService',
  'ElementalAppliancesSoftware',
  'ElementalConductor',
  'ElementalDelta',
  'ElementalLink',
  'ElementalLive',
  'ElementalMediaConvert',
  'ElementalMediaLive',
  'ElementalMediaPackage',
  'ElementalMediaStore',
  'ElementalMediaTailor',
  'ElementalServer',
  'FSxforLustre',
  'FSxforNetAppONTAP',
  'FSxforOpenZFS',
  'FSxforWFS',
  'Fargate',
  'Fargate2',
  'FinSpace',
  'FirewallManager',
  'Forecast',
  'FraudDetector',
  'FrontEndWebMobile',
  'GameKit',
  'GameSparks',
  'GameTech',
  'GlobalAccelerator',
  'GroundStation',
  'GuardDuty',
  'HealthLake',
  'Honeycode',
  'InteractiveVideoService',
  'Kendra',
  'Keyspaces',
  'LakeFormation',
  'LakeFormationDataLake',
  'LaunchWizard',
  'LocalZones',
  'LookoutforEquipment',
  'LookoutforVision',
  'Lumberyard',
  'ManagementGovernance',
  'MigrationTransfer',
  'Monitron',
  'NICEDCV',
  'NICEEnginFrame',
  'Neptune',
  'NetworkingContentDelivery',
  'Neuron',
  'NimbleStudio',
  'NitroEnclaves',
  'Open3DEngine',
  'Outpostsfamily',
  'Panorama',
  'PersonalHealthDashboard',
  'Personalize',
  'Private5G',
  'PrivateLink',
  'ProfessionalServices',
  'Proton',
  'QuantumLedgerDatabase',
  'QuantumLedgerDatabase2',
  'RedHatOpenShift',
  'ResilienceHub',
  'RoboMaker',
  'Robotics',
  'SageMakerGroundTruth',
  'SageMakerStudioLab',
  'Satellite',
  'SavingsPlans',
  'SecurityHub',
  'SecurityIdentityCompliance',
  'ServerContents',
  'Serverless',
  'Signer',
  'SitetoSiteVPN',
  'Snowcone',
  'Snowmobile',
  'SpotFleet',
  'Storage',
  'TensorFlowonAWS',
  'ThinkboxDeadline',
  'ThinkboxFrost',
  'ThinkboxKrakatoa',
  'ThinkboxSequoia',
  'ThinkboxStoke',
  'Timestream',
  'ToolsandSDKs',
  'TorchServe',
  'TrainingCertification',
  'Transcribe',
  'Translate',
  'VMwareCloudonAWS',
  'Wavelength',
  'WellArchitectedTool',
  'WorkLink',
  'rePost',
]);

/**
 * Look up an awslib sprite name and return its mxgraph shape key.
 * Returns null if the sprite has no mxgraph match.
 */
export function lookupAwslibMacro(name: string): AwslibMacroInfo | null {
  const info = AWSLIB_MACROS[name];
  if (!info) return null;
  // Auto-derive resIcon and strokeColor when fillColor is present
  if (info.fillColor) {
    return {
      ...info,
      resIcon: info.resIcon ?? info.shapeKey,
      strokeColor: info.strokeColor ?? WHITE,
    };
  }
  return info;
}

/**
 * Returns true if the name is a known awslib sprite
 * (even if its mxgraph shape is unresolved).
 */
export function isKnownAwslibSprite(name: string): boolean {
  return name in AWSLIB_MACROS || AWSLIB_UNKNOWN.has(name);
}
